<?php
/**
 * AccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ganb\Webhook\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GMO Aozora Net Bank Open API
 *
 * <p>Ph2.5向けに作成したもの</p>
 *
 * OpenAPI spec version: 1.1.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ganb\Webhook\Client;

/**
 * AccountTest Class Doc Comment
 *
 * @category    Class
 * @description 入金口座情報
 * @package     Ganb\Webhook\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Account"
     */
    public function testAccount()
    {
    }

    /**
     * Test attribute "ra_id"
     */
    public function testPropertyRaId()
    {
    }

    /**
     * Test attribute "ra_branch_code"
     */
    public function testPropertyRaBranchCode()
    {
    }

    /**
     * Test attribute "ra_branch_name_kana"
     */
    public function testPropertyRaBranchNameKana()
    {
    }

    /**
     * Test attribute "ra_account_number"
     */
    public function testPropertyRaAccountNumber()
    {
    }

    /**
     * Test attribute "ra_holder_name"
     */
    public function testPropertyRaHolderName()
    {
    }

    /**
     * Test attribute "base_date"
     */
    public function testPropertyBaseDate()
    {
    }

    /**
     * Test attribute "base_time"
     */
    public function testPropertyBaseTime()
    {
    }
}
