<?php
/**
 * SubscribeRequestBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ganb\Webhook\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GMO Aozora Net Bank Open API
 *
 * <p>Ph2.5向けに作成したもの</p>
 *
 * OpenAPI spec version: 1.1.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ganb\Webhook\Client;

/**
 * SubscribeRequestBodyTest Class Doc Comment
 *
 * @category    Class
 * @description SubscribeRequestBody
 * @package     Ganb\Webhook\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscribeRequestBodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubscribeRequestBody"
     */
    public function testSubscribeRequestBody()
    {
    }

    /**
     * Test attribute "subscribe_status"
     */
    public function testPropertySubscribeStatus()
    {
    }

    /**
     * Test attribute "event_types"
     */
    public function testPropertyEventTypes()
    {
    }
}
