<?php
/**
 * VaTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ganb\Webhook\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GMO Aozora Net Bank Open API
 *
 * <p>Ph2.5向けに作成したもの</p>
 *
 * OpenAPI spec version: 1.1.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ganb\Webhook\Client;

/**
 * VaTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description 振込入金口座入金明細情報
 * @package     Ganb\Webhook\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VaTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VaTransaction"
     */
    public function testVaTransaction()
    {
    }

    /**
     * Test attribute "va_id"
     */
    public function testPropertyVaId()
    {
    }

    /**
     * Test attribute "transaction_date"
     */
    public function testPropertyTransactionDate()
    {
    }

    /**
     * Test attribute "value_date"
     */
    public function testPropertyValueDate()
    {
    }

    /**
     * Test attribute "va_branch_code"
     */
    public function testPropertyVaBranchCode()
    {
    }

    /**
     * Test attribute "va_branch_name_kana"
     */
    public function testPropertyVaBranchNameKana()
    {
    }

    /**
     * Test attribute "va_account_number"
     */
    public function testPropertyVaAccountNumber()
    {
    }

    /**
     * Test attribute "va_account_name_kana"
     */
    public function testPropertyVaAccountNameKana()
    {
    }

    /**
     * Test attribute "deposit_amount"
     */
    public function testPropertyDepositAmount()
    {
    }

    /**
     * Test attribute "remitter_name_kana"
     */
    public function testPropertyRemitterNameKana()
    {
    }

    /**
     * Test attribute "payment_bank_name"
     */
    public function testPropertyPaymentBankName()
    {
    }

    /**
     * Test attribute "payment_branch_name"
     */
    public function testPropertyPaymentBranchName()
    {
    }

    /**
     * Test attribute "partner_name"
     */
    public function testPropertyPartnerName()
    {
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
    }

    /**
     * Test attribute "item_key"
     */
    public function testPropertyItemKey()
    {
    }
}
